// app/layout.js
import "bootstrap/dist/css/bootstrap.min.css"; // Bootstrap primeiro
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Depois os estilos globais
import { ModoProvider } from "./context/ModoContext"; // Importa o contexto
import ToggleModoButton from "./components/ToggleModoButton"; // Importa o botão de alternância

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        {/* Ícones do Bootstrap Icons */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ModoProvider>
          {/* Botão de alternância visível no topo de todas as páginas */}
          <div className="container py-3 d-flex justify-content-end">
            <ToggleModoButton />
          </div>
          {children}
        </ModoProvider>
      </body>
    </html>
  );
}
